output "namespace" {
  description = "Namespace where Argo CD was installed"
  value       = kubernetes_namespace.argo.metadata[0].name
}

output "server_service_name" {
  description = "Cluster DNS entry for the Argo CD server service"
  value       = "${var.release_name}-server.${var.namespace}.svc.cluster.local"
}

output "initial_admin_password" {
  description = "Initial admin password generated by Argo CD"
  value       = data.kubernetes_secret.initial_admin.data.password
  sensitive   = true
}
