replicaCount: 2

image:
  repository: "<account-id>.dkr.ecr.us-west-2.amazonaws.com/lesson-7-django-ecr"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

configmap:
  enabled: true
  name: django-app-env
  data:
    DJANGO_SETTINGS_MODULE: "project.settings"
    DJANGO_ALLOWED_HOSTS: "0.0.0.0,127.0.0.1"
    DJANGO_DEBUG: "False"
    DATABASE_HOST: "postgres.default.svc.cluster.local"
    DATABASE_PORT: "5432"
    DATABASE_NAME: "django"
    DATABASE_USER: "django"
    DATABASE_PASSWORD: "replace_me"
    SECRET_KEY: "replace_with_secret"

containerPort: 8000
serviceAccountName: ""
podAnnotations: {}
podLabels: {}
nodeSelector: {}
tolerations: []
affinity: {}
