applications:
  - name: django-app
    project: default
    repo_url: https://github.com/samusdimitriy/HW-DevOps.git
    target_revision: lesson-8-9
    path: lesson-7/charts/django-app
    destination_namespace: django-app
    destination_server: https://kubernetes.default.svc
    create_namespace: true
    helm_value_files: []
    helm_parameters: {}
    sync_policy:
      automated:
        prune: true
        self_heal: true
        allow_empty: false
      sync_options:
        - PrunePropagationPolicy=foreground
        - RespectIgnoreDifferences=true
repositories:
  - name: hw-devops
    url: https://github.com/samusdimitriy/HW-DevOps.git
    type: git
